server:
  context-path: /case
  port: 5020

management:
  security:
    enabled: false
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
spring:
  datasource:
      url: jdbc:mysql://10.49.0.51:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: sunedev
      password: sunedev
      driver-class-name: com.mysql.jdbc.Driver
      platform: mysql
      type: com.alibaba.druid.pool.DruidDataSource
      # 下面为连接池的补充设置，应用到上面所有数据源中
      druid:
        initialSize: 2
        minIdle: 2
        maxActive: 30
      #下面配置说明请参考Druid Github Wiki，配置_StatViewServlet配置
        StatViewServlet:
            loginUsername: druid
            loginPassword: druid
        aop-patterns: com.sunesoft.ecloud.auth.security.service.*
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

